/blue/ruogu.fang/jbroce/GatorBrain/code/finetune
c1106a-s11.ufhpc
Tue Mar  7 22:26:01 EST 2023
WARNING: Skipping mount /scratch/local [binds]: /scratch/local doesn't exist in container
WARNING: Skipping mount /blue [binds]: /blue doesn't exist in container
WARNING: Skipping mount /orange [binds]: /orange doesn't exist in container
WARNING: Skipping mount /bio [binds]: /bio doesn't exist in container
WARNING: Skipping mount /data [binds]: /data doesn't exist in container
WARNING: Skipping mount /data/reference [binds]: /data/reference doesn't exist in container
WARNING: Skipping mount /data/ai [binds]: /data/ai doesn't exist in container
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: numpy in /opt/conda/lib/python3.8/site-packages (1.24.2)

[notice] A new release of pip available: 22.2 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (478) bind mounts
Found GPU
Python version 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0]
1.13.0a0+340c412
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (478) bind mounts
In the future `np.bool` will be defined as the corresponding NumPy scalar.
In the future `np.bool` will be defined as the corresponding NumPy scalar.
In the future `np.bool` will be defined as the corresponding NumPy scalar.
In the future `np.bool` will be defined as the corresponding NumPy scalar.
Successfully loaded checkpoint, beginning finetune...
----------
epoch 1/5
Traceback (most recent call last):
  File "./finetune.py", line 148, in <module>
    accuracy = run_training(model,
  File "/blue/ruogu.fang/jbroce/GatorBrain/code/finetune/trainer.py", line 28, in run_training
    outputs = model(inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/ruogu.fang/jbroce/GatorBrain/code/finetune/model.py", line 20, in forward
    out = self.final_layer(flattened_out)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/monai/monai/data/meta_tensor.py", line 245, in __torch_function__
    ret = super().__torch_function__(func, types, args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 1121, in __torch_function__
    ret = func(*args, **kwargs)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x9633792 and 1x2)
